### ISSUE TITLE
Next steps and issues

### ISSUE THREAD

**Issue by darylnak** [darylnak/SEE-Lab#1]
Based on [this](https://youtu.be/5sijxSg8P14?list=PL-gyhFHJAuGZjMCs7WTC84rPN4IG5_07Q&t=913) video, I understand MMD as the squared L2 norm between two feature means. In the context of this problem, while reading the data, I build a vector `feature_vector` such that for every window `X_w`, the corresponding entry in `feature_vector` is a 3-tuple `(band_relpower, means, variances)`, where `band_relpower` is a 1D vector with 10 values, `means` is a 1D vector with 2 values that are the means for the two channels, and `variances` being similar to `means`. Then, I perform `np.vstack(feature_vector)`, which create an N x 14 vector. **Using this information, I assume each window is iid. I go through all seizure and non-seizure data and separate each training datum into their respective category. Then, I average the `band_relpower`, `means`, and `variances` for seizure and non-seizure data. Then instead of performing logistic regression, I use MMD and our two averaged vectors as the model, i.e. I compute the squared L2 norm between each validation point and the averaged seizure and non-seizure vector, then classify the point as the category which gave the minimum distance.**

Is the bolded portion correct?

**Comment by thomas9t** [comment]
Thanks @darylnak! A few comments/thoughts:

> I understand MMD as the squared L2 norm between two feature means

This is correct! However, there's a bit of extra subtlety here. The ability of the MMD to differentiate two distributions depends heavily on the feature map used to transform the data. As a simple example, consider the identity map which just returns the original vector. Then the MMD is just measuring the distance between the data's mean. Now suppose we have two distributions with equal mean but different variance. These are different distributions but the MMD using the identity map will not be able to differentiate them. If we take the feature map to be a second order polynomial then the MMD can differentiate based on mean and variance, but not 3rd order moments. To get the most powerful form of MMD we actually need an _infinite dimensional_ feature map. That's where the kernel function comes in. We can think of a kernel function as a two step process. First, we "lift" the data into a high dimensional space under a feature map `g(x)`. Then we compute an inner product between two vectors in this space: `k(x,y) = <g(x),g(y)>` where `<x,y>` denotes the inner product. The useful thing about kernels is that we do not have to explicitly evaluate `g(x)`. This means we can use Kernels to compute inner products in an infinite dimensional space! So the MMD is usually defined using a kernel. See the wikipedia article [here](https://en.wikipedia.org/wiki/Kernel_embedding_of_distributions). The "radial basis function" kernel is a good choice since one can show that it allows the MMD to differentiate any pair of (reasonable) distributions. So a very naive (and very slow) implementation of the MMD (assuming equal sample sizes) would be something like the following:

```
def mmd(X,Y):
    Kxx = 0
    Kxy = 0
    Kyy = 0
    N = X.shape[0]
    for ii in range(N):
        for jj in range(ii+1, N):
            Kxx += k(X[ii], X[jj])
            Kyy += k(Y[ii], Y[jj])
            Kxy += k(X[ii], Y[jj])
    return (1/N**2)*Kxx + (1/N**2)*Kyy - (2/N**2)*Kxy
```
But this will be extremely slow.

> Using this information, I assume each window is iid. I go through all seizure and non-seizure data and separate each training datum into their respective category.

Correct!

> Then, I average the band_relpower, means, and variances for seizure and non-seizure data.

Not quite - see the comment above about MMD and kernels. The empirical MMD is described in the section of the Wikipedia article I linked above called "A Kernel Two-Sample Test"

> then classify the point as the category which gave the minimum distance

Correct!

Let me know if you have any other questions!

**Comment by darylnak** [comment]
Great note @thomas9t. I am currently reading the Kernel Methods section in the book you lent me to develop a better understanding of the math behind this.

**Comment by thomas9t** [comment]
Sounds good!

**Comment by thomas9t** [comment]
Hey @darylnak - how's everything going? Maybe it would be a good idea to meet later this week just to go over some of the theory behind kernel methods and MMD?

**Comment by darylnak** [comment]
@thomas9t Yes! I am having difficulty understanding what Φ(x) should be and how one decides. Does the usual time work?

**Comment by thomas9t** [comment]
@darylnak maybe - can you remind me what the usual time is again?

**Comment by darylnak** [comment]
@thomas9t Does Friday at 1pm work?

**Comment by thomas9t** [comment]
Yeah sure

**Comment by darylnak** [comment]
@thomas9t 

See my writeup [here](https://www.overleaf.com/read/wfxjmynntvys). Let me know what you think.

**Lingering question:**  What is the most efficient way to find universal kernels online? Most of my searches present research papers, leading me to believe I need to skim through each. 

UPDATE 1: Fixed missing (-) sign in formula 1
